// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleScssNamespace {
    export interface IStyleScss {
        container: string;
        "greciept-form": string;
        p: string;
        "two-thirds": string;
    }
}

declare const StyleScssModule: StyleScssNamespace.IStyleScss;

export = StyleScssModule;
